[window]
fullscreen = true

[demo]
mode = "random"
effect_duration = 180
transition = "shuffle"

[audio]
reactivity = 3.0
latency = "low"
try_alsa_loopback = false

[ansi]
ansi_dir = "assets/ansi/acid"
ansi_own_dir = "assets/ansi"
ansi_acid_dir = "assets/ansi/acid"

[splash]
duration_audio = 7.0
duration_silent = 4.0

[playlist]
start_effect = "Audio Spectrum"
